name: lando-code-server
recipe: mean
config:
  node: 14
  command: npm start
  port: '3000'
services:
  appserver:
    overrides:
      ports:
        - 5555:5555
  codeserver:
    user: root
    type: compose
    app_mount: false
    services:
      image: codercom/code-server
      ports:
        - 8080
      environment:
        - "DOCKER_USER=${USER}"
      volumes:
        - ./.config/code-server:/home/coder/.config/code-server
        - ./.local/code-server:/home/coder/.local/share/code-server
        - ./:/home/coder/project
        - "${HOME}/.ssh/:/home/coder/.ssh"
      command: entrypoint.sh /home/coder/project
      extra_hosts:
      - host.docker.internal:host-gateway
proxy:
  appserver:
    - lando-code-server.lndo.site:3000
  codeserver:
    - lando-code-server-cdr.lndo.site:8080
